"""Update Level model with image_url

Revision ID: e8557a634421
Revises: 
Create Date: 2025-04-18 07:54:54.943692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8557a634421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint('sections_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sections_ibfk_1', 'levels', ['level_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
